name: traveltrek_tourist_app
description: TravelTrek Smart Tourist Safety & Incident Response System - Mobile App.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.0
  riverpod_annotation: ^2.3.0
  go_router: ^13.0.0
  dio: ^5.4.0
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  geolocator: ^11.0.0
  flutter_background_service: ^5.0.0
  flutter_blue_plus: ^1.31.0
  nearby_connections: ^4.0.0
  flutter_sms: ^2.3.0
  qr_flutter: ^4.1.0
  mapbox_maps_flutter: ^2.0.0
  turf: ^0.0.11
  crypto: ^3.0.3
  connectivity_plus: ^6.0.0
  flutter_local_notifications: ^17.0.0
  workmanager: ^0.5.2
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  speech_to_text: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
