name: traveltrek_tourist_app
description: TravelTrek Smart Tourist Safety & Incident Response System - Mobile App.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.1.0
  flutter_riverpod: ^2.5.0
  riverpod_annotation: ^2.3.0
  go_router: ^13.0.0
  dio: ^5.4.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  flutter_secure_storage: ^9.0.0
  geolocator: ^11.0.0
  flutter_background_service: ^5.0.0
  flutter_blue_plus: ^1.31.0
  nearby_connections: ^4.0.0
  flutter_sms: ^3.0.1
  qr_flutter: ^4.1.0
  mapbox_maps_flutter: ^2.0.0
  turf: ^0.0.11
  crypto: ^3.0.3
  connectivity_plus: ^6.0.0
  battery_plus: ^6.0.2
  flutter_local_notifications: ^17.0.0
  workmanager: ^0.9.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  speech_to_text: ^7.4.0
  url_launcher: ^6.2.0
  intl: ^0.19.0
  permission_handler: ^12.0.1
  screen_brightness: ^1.0.1
  audioplayers: ^6.0.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "app_icon.png"
  min_sdk_android: 21
