export default function Alerts() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-slate-100">Alerts Triage Centre</h1>
        <p className="text-slate-400 mt-1">Manage and resolve active distress signals, system advisories, and warning broadcasts.</p>
      </div>
      <div className="glass-panel p-8 rounded-xl text-center space-y-4">
        <p className="text-slate-400">All emergency SOS signals generated by tourists are logged and managed here.</p>
      </div>
    </div>
  );
}
